config/routes.rb
Rails.application.routes.draw do

  get 'passwords/change'

  	get 'created_accounts/index'

	put '/biddings/:id', to: 'biddings#set_as_winning', as: "bidding"
	get '/biddings/list_active', to: "biddings#list_active"
	patch '/biddings/:id', to: "biddings#update"

	get '/products/concluded', to: "products#concluded"
	get '/products/my_auctions', to: "products#my_auctions"

	resources :products do
		resources :biddings
		resources :inquiries
	end

	root "products#index"
	
	devise_for :users, :controllers => { registrations: 'registrations' }
	resources :users, :only => [:index]
	resources :categories, :except => [:show, :destroy]

end

app/models/bidding.rb
class Bidding < ActiveRecord::Base

	include BiddingsHelper
	
  belongs_to :product
  belongs_to :user

  validates :reason, presence: true, length: {:maximum => 250}
  validates :amount, presence: true
  validates_numericality_of :amount, greater_than: 0
end

app/controllers/biddings_controller.rb
class BiddingsController < ApplicationController
	
	before_action :authenticate_user!


	def index
		@biddings = Product.find(params[:product_id]).biddings_with_user
	end

	def create
		@product = Product.find(params[:product_id])
		@bidding = @product.biddings.create(params[:bidding].permit(:reason, :amount))
		@bidding.user_id = current_user.id if current_user
		
		if @bidding.save
			redirect_to product_path(@product)
			flash[:notice] = "Se ha ofertado con éxito!"
		else
			flash[:invalid] = "Debe ingresar un motivo y monto válidos."
			redirect_to product_path(@product)
		end
	end

	def update
		@biddings = current_user.biddings
		@bidding = Bidding.find_by(id: params[:id])

		if !bidding_params[:amount].blank? && @bidding.update(bidding_params)
    	flash[:notice] = "Monto actualizado con éxito!"
    else
    	flash[:invalid] = "Por favor, ingrese un monto válido."
    end

    @biddings_to_list = current_user.biddings_without_winner
    
    render 'list_active'
		
	end

	def set_as_winning
		@bidding = Bidding.find(params[:id])
		@bidding.update(:is_winner => true)
		@bidding.product.update(:state => 'finished')
		redirect_to product_path(@bidding.product.id)
		flash[:notice] =  "Ud. ha elegido un ganador! Estamos procesando el cobro de su comisión. Gracias por operar con nosotros!"
	end

	def list_active
		#@biddings_to_list = current_user.biddings_without_winner
		@biddings_to_list = current_user.biddings
	end

	private

	def bidding_params
		params.require(:bidding).permit(:amount)
	end

end

app/helpers/biddings_helper.rb
module BiddingsHelper

end

app/views/biddings/_bidding.html.erb
<div id="biddings">
	<% @biddings.each do |bidding| %>
		<div class="bidding">
			<h2 class="user">
				<%= bidding.user ? bidding.user.name : "Usuario cancelado"%>
			</h2>
			<p class="reason">
				<%= bidding.reason %>
			</p>
				<%= link_to 'Seleccionar como ganador', bidding_path(bidding.id), :method => :put %>
			<hr>
		</div>
	<% end %>
</div>

app/views/biddings/_form.html.erb
<div>
  <div>
    <h3>Ofertar por el producto</h3>
    <%= simple_form_for([@product, @product.biddings.build]) do |f| %>
      <div class="form-group">
        <%= f.input :reason, label: 'Razón:', placeholder: "Escriba la razón por la cual piensa que merece el producto.",required: true, input_html: { class: 'form-control' } %>
      </div>
      <div class="form-group">
        <%= f.input :amount, label: 'Monto: $', placeholder: "Ingrese un monto para el producto.", required: true, input_html: { class: 'form-control' } %>
      </div>
      <%= f.button :submit, 'Ofertar', { class: "btn btn-primary" }%>
    <% end %>
  </div>
</div>

app/views/biddings/index.html.erb
<h2>Lista de ofertas del producto subastado:</h2>

<%= render 'bidding' %>

app/views/biddings/list_active.erb
<div class="title" align="center"><h2>Mis Ofertas</h2></div>

<div class="transitions-enabled" id="products">

<div id="biddings">

<% if @biddings_to_list.any? %>
	<% @biddings_to_list.each do |bidding| %>
		
	<div class="box panel panel-default">

		<div class="bidding">
			<p><h3><%= bidding.product.name %></h3></p>
			<p>Subastado por <%= bidding.product.user ? bidding.product.user.name : "Usuario cancelado" %></p>

			<%= link_to ( image_tag bidding.product.image.url ), bidding.product %>
		<p>Tu motivo: <%= bidding.reason %></p>
		<% if bidding.product.has_winner? %>
			<% if bidding.product.winner == current_user %>
				<div style= "color: blue; font-weight:bold; font-size: 20px;">Ganaste la subasta!</div>
			<% else %>
				<div style= "color: red;">El subastador ya ha elegido ganador.</div>
			<% end %>
		<% else %>			
			  <%= simple_form_for ([@product, bidding])  do |f| %>
			    <div class="form-group">
			    	<p>Monto ofrecido por tí: $<%= bidding.amount %></p>
			      <%= f.input :amount, label: false, required: true, input_html: { class: 'form-control'} %>
			    
			    <%= f.button :submit, 'Cambiar', { class: "btn btn-primary" }%>
			  	</div>
			  <% end %>
		<% end %>

		</div>
		</div>

	</div>

	<% end %>
	<% else %>
		<h2><%= "Usted no tiene ofertas" %></h2>
	<% end %>
</div>

</div>