config/routes.rb
Rails.application.routes.draw do

  get 'passwords/change'

  	get 'created_accounts/index'

	put '/biddings/:id', to: 'biddings#set_as_winning', as: "bidding"
	get '/biddings/list_active', to: "biddings#list_active"
	patch '/biddings/:id', to: "biddings#update"

	get '/products/concluded', to: "products#concluded"
	get '/products/my_auctions', to: "products#my_auctions"

	resources :products do
		resources :biddings
		resources :inquiries
	end

	root "products#index"
	
	devise_for :users, :controllers => { registrations: 'registrations' }
	resources :users, :only => [:index]
	resources :categories, :except => [:show, :destroy]

end

app/models/product.rb
class Product < ActiveRecord::Base
	#after_initialize :init
	before_save :set_due_date
	belongs_to :user
	belongs_to :category
	has_many :biddings
	has_many :inquiries
 
	validates :name, presence: true, uniqueness: true, length: {:maximum => 25}
	validates :description, presence: true, length: {:maximum => 750}
	validates_presence_of :image, :message => :required
	validates :category_id, presence: true
	
	include ProductsHelper

	attr_reader :period

	#STATES = ['active', 'blocked', 'finished']

	has_attached_file :image, styles: {medium: "300x300>"}
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
	#validates_inclusion_of :state, :in => STATES, :message => "{{value}} must be in #{STATES.join ','}"

	def set_due_date
		self.due_date ||= due_date_for(self.period)
	end

=begin
	def init
		self.state = 'active'
	end
=end

	def self.search(search)
   		where("name like ?", "%#{search}%") 
    end

	def period=(value)
		@period = value.to_i
	end

	#def self.get_concluded
	#	self.all.select { |p| p.has_winner? }
	#end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

	before_action :find_product, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]
	before_action :get_categories, only: [:new, :create]


	def index
	  if params[:search]
	  	params[:sort] ||= "name"
	    @products = Product.search(params[:search]).order(params[:sort])
	  elsif (params[:sort].eql? "name")
	  	@products = Product.order('lower(name)')
	  else
	  	@products = Product.order(params[:sort])
	  end
	end

	def concluded
  	
  	if params[:search_dates]

			date_from = params[:search_dates][:date_from]
			date_to = params[:search_dates][:date_to]

			if date_from <= date_to
				date_to += ' 23:59:59.999999'				
				@winners = Bidding.where(is_winner: true)
				@biddings = @winners.where(
					"created_at >= :date_from AND created_at <= :date_to",
  				{date_from: date_from, date_to: date_to}
  				)

				@products = @biddings.map { |b| b.product }
				flash.now[:notice] = "Se ha generado el reporte."
			else
				@products = []
				flash[:invalid] = "Por favor, ingrese un rango de fechas válido."
			end

		else
			@products = []
			flash[:notice] = "Bienvenido al reporte de subastas concluidas"
		end

		render 'concluded'
	end

	def my_auctions
		@products = current_user.products.order("state DESC")
	end

	def new
		@product = current_user.products.build
	end

	def create
		@product = current_user.products.build(product_params)

		if @product.save
			flash[:notice] =  "Subasta creada!"
			redirect_to @product
		else
			render 'new'
		end
	end

	def show
		@inquiries = @product.inquiries
	end

	def edit
	end

	def update
		if @product.update(product_params)
			flash[:notice] = "Actualizado con exito!"
			redirect_to @product
		else
			render 'edit'
		end
	end

	def destroy
		@product.destroy
		redirect_to root_path
	end


	private

	def product_params
		params.require(:product).permit(:name, :description, :state, :period, :image, :category_id)
	end

	def find_product
			@product = Product.find_by(id: params[:id])
		
		if !@product
			redirect_to root_path
			flash[:notice] =  "Lo sentimos. No se pudo procesar su solicitud."
		end
	end

	def get_categories
		@categories = Category.where("hidden = ?", false).order("name")

		if !@categories
			redirect_to root_path
			flash[:notice] = "Lo sentimos. No se pudo procesar su solicitud."
		end
	end


end

app/helpers/products_helper.rb
module ProductsHelper

	include BestnidHelper

	def due_date_for(validity_period)
		validity_period.days.from_now
	end

	def criteria_for(field)
		criteria = {
			"name" => "Nombre",
			"due_date" => "Fecha de Finalización",
			"created_at" => "Fecha de Publicación"
		}
		criteria[field]
	end

	def is_cancellable?
		current_user == @product.user && @product.biddings.size == 0
	end

	def winner
		winning_bidding = self.biddings.find {|b| b.is_winner?}
		winning_bidding ? winning_bidding.user : nil
	end

	def has_winner?
		!self.winner.nil?
	end
	
	def has_biddings?
		!self.biddings.empty?
	end

	def refresh_state
		if self.state = 'active'
			self.state = 'finished' if Time.today.date > self.due_date
		end
	end

	def biddings_with_user #biddings excluding any biddings made by a canceled user account
		self.biddings.all.select { |b| User.all.include? b.user }
	end

end

app/views/products/_concluded.html.erb
<h3>Total de subastas encontradas: <%= @products.size %></h3>

<% income = if @products.any?
							@products.map do |p| 
								p.biddings 
							end.flatten.select do |b| 
								b.is_winner? end.inject(0) do |sum, b| 
									sum + (b.amount * 0.3) 
								end
						else
							0
						end
%>

	<h3>Total ganado en comisiones: $ <%= print_money income %></h3>
<div class="transitions-enabled" id="products">

<% @products.each do | product | %>
<div class="box panel panel-default">
	<%= link_to (image_tag product.image.url), product %>
	<p>
		<%= link_to product.name, product %>
	</p>
	<p>
		Comisión obtenida: $<%= print_money product.biddings.where(is_winner:true).first.amount * 0.3 %>
	</p>
	<p>
		Concluida el <%= product.biddings.where(is_winner: true).first.updated_at.to_date %>
	</p>
	<br>
<% end %>

</div>

</div>

app/views/products/_form.html.erb
<%= simple_form_for @product, html: { multipart: true } do |f| %>
  <div class="form-group">
    <%= f.input :image, label: 'Foto del Producto:', required: true, input_html: { class: 'form-control' } %>
  </div>
  <div class="form-group">
    <%= f.input :name, label: 'Nombre del Producto:', required: true, placeholder: "Escriba un nombre para el producto.",:error_html => {:id => "name_prod_error"} , input_html: { class: 'form-control' } %>
  </div>
  <div class="form-group">
    <%= f.input :category_id, label: 'Categoría:', :collection => @categories, :value_method => :id %>
    <%= f.input :description, label: 'Descripción del Producto:', placeholder: "Ingrese una descripción detallada del producto a subastar.", input_html: { class: 'form-control' } %>
    <%= f.input :period, label: 'Duración de la subasta en días:', required: true, collection: 15..30, default: 15%>
  </div>
  <div data-no-turbolink>
    <%= f.button :submit, 'Crear Subasta', { class: "btn btn-primary" }%>
    <%= link_to "Cancelar", root_path, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/products/concluded.html.erb
<h2> Subastas concluidas </h2>


<div class="body">
		<div class="search">
	<%= form_tag("/products/concluded", method: "get") do %>
		<%= label_tag(:date_from, "Desde") %>
		<%= date_field(:search_dates, :date_from, value: params[:date_from], required: true) %>
		<%= label_tag(:date_to, "Hasta") %>
		<%= date_field(:search_dates, :date_to, value: params[:date_to], required: true) %>
		<%= submit_tag "Obtener Reporte"%>
	<% end %>
		</div>

	<div class="list">
		<%= render 'concluded' %>
	</div>

</div>

app/views/products/edit.html.erb
<div class="col-md-8 col-md-offset-2" id="edit_page">
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h1>Editar Subasta</h1>
      </div>
      <div class="panel-body">
        <div class="current_image">
          <strong class="center">Imagen actual:</strong>
          <%= image_tag @product.image.url(:medium) %>
        </div>
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/products/index.html.erb
<% if @products.present? %>
<% params[:sort] ||= "name" %>

<div class="sorting-options">Ordenado por <%= (criteria_for params[:sort]) %>
	<div data-no-turbolink>
		  <%= link_to "Ordenar por Nombre", sort: "name", search: params[:search] %> - 
		  <%= link_to "Ordenar por Fecha de Publicación", sort: "created_at", search: params[:search] %> - 
		  <%= link_to "Ordenar por Fecha de Finalización", sort: "due_date", search: params[:search] %>
  </div>
</div>

	<div class="transitions-enabled" id="products">

	  <% @products.each do |product| %>
	    <div class="box panel panel-default">
	      <%= link_to (image_tag product.image.url), product %>
	      <h2>
	      	<%= link_to product.name, product %>
	      	<% if product.state == 'finished' %>
	      		<h2 style= "color: red;"> SUBASTA FINALIZADA</h2>
	      	<% end %>
	      </h2>
	      <hr>
	      <p>Subastado por <%= product.user ? product.user.name : "un usuario dado de baja" %></p>
	      <p class="categoria">En <%= Category.find_by(id: product.category_id).name %></p>
	      <p>Fecha de finalización: <%= l(product.due_date, format: "%d %b %Y") %></p>
	    </div>
	  <% end %>
	  
	</div>

<% else %>
	<% if params[:search] %>
		<p id="no_coincide"> No hay productos que coincidan con <%= params[:search] %> </p>
	<% else %>
		<p id="no_hay"> No hay productos cargados </p>
	<% end %>
<% end %>

app/views/products/my_auctions.html.erb
<div class="title" align="center"><h2>Mis Subastas</h2></div>

	<div class="transitions-enabled" id="products">

<% if @products.any? %>
	<% @products.each do |p| %>
	<div class="box panel panel-default">
			<%= link_to (image_tag p.image.url, { :height => 150, :crop => :fill }), p  %>	
			<p><%= link_to p.name, p %></p>
			<% if p.state == "active" %>
				<p>Subasta activa</p>
			<% else %>
				<p>Subasta finalizada</p>
			<% end %>
	</div>
	<% end %>
<% else %>
	<h2>Usted no tiene subastas creadas.</h2>
<% end %>

</div>

app/views/products/new.html.erb
<div class="col-md-8 col-md-offset-2">
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h1>Nueva Subasta</h1>
      </div>
      <div class="panel-body">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/products/show.html.erb
<div class="row" id="product_show">
  <div class="col-md-8 col-md-offset-2">
    <div class="panel panel-default">
      <div class="panel-heading product_image">
        <%= image_tag @product.image.url %>
      </div>
      
      <div class="panel-body">
        <h1>
          
          <% winner = @product.winner %>

          <%= @product.name %><br>

          <% if  @product.state == 'finished' %>
               <h1 style= "color: red;"> SUBASTA FINALIZADA</h1>
          <% end %>

          <% if !winner %>
            <% if current_user == @product.user && @product.state == 'finished' %>
              <% unless @product.biddings_with_user.empty? %>
                   <%= link_to "Ver Ofertas", product_biddings_path(:product_id => @product.id, :bidding_id => @bidding_id), { class: "btn btn-primary" } %>
              <% end %>
            <% end %>
          <% else %>
            <h1 style= "color: blue;">
              <%= "Ganador de la subasta: #{winner.name}" %>
            </h1>
          <% end %>

        </h1><br>

        <h2>
        <% if is_cancellable? %>
         <%= link_to "Cancelar Subasta", product_path, method: :delete, data: { confirm: "¿Estas seguro?" } %>
        <% end %>
        </h2>

        <h3>Esta subasta finaliza el día: <%= l(@product.due_date,format: "%d %b %Y") %></h3>
        <br>
        <p class="description">
          <%= @product.description %>
          <hr>
        </p>
        <p class="user">
          Subastado por
          <%= @product.user ? @product.user.name : "Usuario cancelado" %>
        </p>
        <p class="categoria">En
          <%= Category.find_by(id: @product.category_id).name %>
        </p>
      <% if current_user && current_user.email != 'admin@test.com' %>
        <% if current_user != @product.user && @product.state == 'active' %>
          <% unless @product.biddings.find_by(:user => current_user) %>
              <div class="panel-footer">
                <div class="row">
                  <%= render "biddings/form" if current_user %>
                </div>
              </div>
          <% end %>  
        <% end %>
      <% end %>
      <% if current_user && current_user.email != 'admin@test.com' %>
        <div class="panel-footer inquiries">
          <%= render 'inquiries/list' %>
        </div> 
      <% end %>
    </div>
  </div>
</div>